# Generated by Django 5.0 on 2024-01-02 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_active_code',
            new_name='verification_code',
        ),
    ]
